#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/students_details
#    driver-class=com.cj.jdbc.Driver
#    username: root
#    password: Bala@2468
#    
#  #jpa configuration
#  jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#  jpa.hibernate.ddl-auto=update
#  jpa.show-sql=true
#  jpa.properties.hibernate.formate_sql=true;  
#  sql.init.platform : mysql
 